name: CI-Main

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Log in to GHCR
      - name: Log in to GHCR
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # 3️⃣ Build backend image (latest)
      - name: Build Backend Image
        run: docker build -t ghcr.io/${{ github.repository }}/backend:latest ./backend

      # 4️⃣ Build frontend image (latest)
      - name: Build Frontend Image
        run: docker build -t ghcr.io/${{ github.repository }}/frontend:latest ./frontend

      # 5️⃣ Push backend image
      - name: Push Backend Image
        run: docker push ghcr.io/${{ github.repository }}/backend:latest

      # 6️⃣ Push frontend image
      - name: Push Frontend Image
        run: docker push ghcr.io/${{ github.repository }}/frontend:latest
  #  Copy docker-compose.yml to EC2
      - name: Copy docker-compose.yml to EC2
        uses: appleboy/scp-action@v0.1.5
        with:
          host: 15.216.159.194          # server IP
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: docker-compose.yml
          target: ~/secrecto_web_live/docker-compose.yml

      # 7️⃣ Copy docker-compose.yml to EC2
      - name: Copy docker-compose.yml to EC2
        uses: appleboy/scp-action@v0.1.5
        with:
          host: YOUR_EC2_IP          # replace with your server IP
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: docker-compose.yml
          target: ~/secrecto_web_live/docker-compose.yml

      # 8️⃣ Deploy on EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: YOUR_EC2_IP
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd secrecto_web_live
            docker compose pull
            docker compose up -d
